[package]
name = "christian-toney/edtw-stage"
description = "A class for servers to easily parse and edit stages in Everyone Destroys the World."
version = "1.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
repository = "https://github.com/EveryoneDestroysTheWorld/stage"
authors = ["Christian Toney <christian.toney@beastslash.com>"]
include = ["src", "src/**/*.lua", "wally.toml", "default.project.json"]
exclude = ["**"]

[dependencies]
